# Generated by Django 3.0.7 on 2020-07-04 00:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrpgSession',
            fields=[
                ('trpg_session_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trpg_session_name', models.CharField(max_length=255, verbose_name='セッション名')),
            ],
            options={
                'verbose_name': 'セッション名',
                'verbose_name_plural': 'セッション名',
            },
        ),
        migrations.CreateModel(
            name='SessionUsers',
            fields=[
                ('session_user_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='ユーザー名')),
                ('ticket_no', models.CharField(max_length=8, verbose_name='チケットNO')),
                ('trpg_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appv1.TrpgSession')),
            ],
            options={
                'verbose_name': 'ユーザー',
                'verbose_name_plural': 'ユーザー',
            },
        ),
        migrations.CreateModel(
            name='DiceRoll',
            fields=[
                ('dice_roll_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('twitter_users_photo', models.CharField(blank=True, max_length=255)),
                ('roll_dice_command', models.CharField(max_length=255)),
                ('roll_target', models.CharField(blank=True, max_length=255)),
                ('roll_dice_result_split', models.CharField(blank=True, max_length=8)),
                ('roll_dice_result_sum', models.CharField(blank=True, max_length=8)),
                ('is_roll_daice_suees', models.BooleanField(blank=True, default=False)),
                ('is_roll_dice_resultresul_fumble', models.BooleanField(blank=True, default=False)),
                ('is_roll_dice_resultresul_critical', models.BooleanField(blank=True, default=False)),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
                ('session_users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appv1.SessionUsers')),
            ],
            options={
                'verbose_name': 'ダイスログ',
                'verbose_name_plural': 'ダイスログ',
            },
        ),
    ]
