# Generated by Django 3.0.8 on 2020-08-09 09:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrpgSession',
            fields=[
                ('trpg_session_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trpg_session_name', models.CharField(max_length=255, verbose_name='セッション名')),
                ('trpg_session_outline', models.TextField(blank=True, max_length=5000, verbose_name='セッション概要')),
                ('trpg_session_image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('trpg_session_bgm', models.FileField(blank=True, null=True, upload_to='bgm')),
            ],
            options={
                'verbose_name': 'セッション',
                'verbose_name_plural': 'セッション',
            },
        ),
        migrations.CreateModel(
            name='SessionUsers',
            fields=[
                ('session_user_id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='ユーザー名')),
                ('ticket_no', models.CharField(max_length=8, verbose_name='チケットNO')),
                ('character_image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('character_name', models.CharField(max_length=255, verbose_name='キャラ名')),
                ('character_profile', models.TextField(max_length=2000, verbose_name='キャラプロフィール')),
                ('tw_UID', models.CharField(blank=True, max_length=50, verbose_name='twetter UID')),
                ('tw_name', models.CharField(blank=True, max_length=50, verbose_name='twetter Name')),
                ('tw_photo', models.CharField(blank=True, max_length=255, verbose_name='twetter Photo')),
                ('trpg_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appv1.TrpgSession')),
            ],
            options={
                'verbose_name': 'ユーザー',
                'verbose_name_plural': 'ユーザー',
            },
        ),
        migrations.CreateModel(
            name='SessionScene',
            fields=[
                ('session_scene_id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('scene_name', models.CharField(max_length=255, verbose_name='シーン名')),
                ('scene_no', models.CharField(max_length=8, verbose_name='シーンNO')),
                ('scene_image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('scene_outline', models.TextField(blank=True, max_length=5000, verbose_name='シーン概要')),
                ('scene_bgm', models.FileField(blank=True, null=True, upload_to='bgm')),
                ('trpg_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appv1.TrpgSession')),
            ],
            options={
                'verbose_name': 'シーン',
                'verbose_name_plural': 'シーン',
            },
        ),
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('memo_id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('memo_title', models.CharField(max_length=255, verbose_name='メモタイトル')),
                ('memo_value', models.TextField(max_length=2000, verbose_name='メモ')),
                ('memo_image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('session_scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appv1.SessionScene')),
            ],
            options={
                'verbose_name': 'メモ',
                'verbose_name_plural': 'メモ',
            },
        ),
        migrations.CreateModel(
            name='ItemMaster',
            fields=[
                ('item_master_id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('item_name', models.CharField(blank=True, max_length=255, verbose_name='アイテム名')),
                ('item_image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('item_explanation', models.TextField(blank=True, max_length=5000, verbose_name='アイテム説明')),
                ('trpg_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appv1.TrpgSession')),
            ],
            options={
                'verbose_name': 'アイテムマスタ',
                'verbose_name_plural': 'アイテムマスタ',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('item_count', models.IntegerField(verbose_name='数')),
                ('item_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appv1.ItemMaster')),
                ('item_owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='appv1.SessionUsers')),
            ],
            options={
                'verbose_name': 'アイテム',
                'verbose_name_plural': 'アイテム',
            },
        ),
        migrations.CreateModel(
            name='DiceRoll',
            fields=[
                ('dice_roll_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('twitter_users_photo', models.CharField(blank=True, max_length=255)),
                ('twitter_users_name', models.CharField(blank=True, max_length=255)),
                ('roll_dice_command', models.TextField(max_length=2000)),
                ('roll_target', models.CharField(blank=True, max_length=255)),
                ('roll_dice_result_split', models.CharField(blank=True, max_length=255)),
                ('roll_dice_result_sum', models.CharField(blank=True, max_length=8)),
                ('is_roll_daice_suees', models.BooleanField(blank=True, null=True)),
                ('is_roll_dice_resultresul_fumble', models.BooleanField(blank=True, default=False)),
                ('is_roll_dice_resultresul_critical', models.BooleanField(blank=True, default=False)),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
                ('session_users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appv1.SessionUsers')),
            ],
            options={
                'verbose_name': 'ダイスログ',
                'verbose_name_plural': 'ダイスログ',
            },
        ),
    ]
