# Generated by Django 3.0.8 on 2020-08-16 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appv1', '0002_auto_20200814_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='trpgsession',
            name='trpg_session_now_scene',
            field=models.UUIDField(null=True, verbose_name='現在のシーン'),
        ),
    ]
