# Generated by Django 3.0.8 on 2020-08-16 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appv1', '0003_trpgsession_trpg_session_now_scene'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trpgsession',
            name='trpg_session_bgm',
        ),
        migrations.RemoveField(
            model_name='trpgsession',
            name='trpg_session_image',
        ),
    ]
