# Generated by Django 3.0.7 on 2020-07-10 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appv1', '0003_auto_20200710_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionusers',
            name='character_image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
