# Generated by Django 3.0.8 on 2020-08-19 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appv1', '0004_auto_20200816_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionusers',
            name='is_session_master',
            field=models.BooleanField(default=False),
        ),
    ]
