# Generated by Django 3.0.8 on 2020-08-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appv1', '0005_sessionusers_is_session_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='trpgsession',
            name='firebase_message_key_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trpgsession',
            name='firebase_scean_key_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
