# Generated by Django 3.0.7 on 2020-07-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appv1', '0005_auto_20200711_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionusers',
            name='tw_UID',
            field=models.CharField(blank=True, max_length=50, verbose_name='twetter UID'),
        ),
        migrations.AddField(
            model_name='sessionusers',
            name='tw_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='twetter Name'),
        ),
        migrations.AddField(
            model_name='sessionusers',
            name='tw_photo',
            field=models.CharField(blank=True, max_length=50, verbose_name='twetter Photo'),
        ),
    ]
