# Generated by Django 3.0.7 on 2020-07-12 11:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appv1', '0006_auto_20200712_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionusers',
            name='session_user_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
