# Generated by Django 3.0.8 on 2020-09-24 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appv1', '0007_auto_20200914_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionusers',
            name='handout',
            field=models.TextField(blank=True, max_length=2000, verbose_name='ハンドアウト'),
        ),
    ]
