# Generated by Django 3.0.8 on 2020-07-14 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appv1', '0007_auto_20200712_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionusers',
            name='tw_photo',
            field=models.CharField(blank=True, max_length=255, verbose_name='twetter Photo'),
        ),
    ]
